import os
import json
import glob
import numpy as np
from collections import defaultdict, Counter
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score

BASE = r"D:\KMAR-50K\KMAR-50K"
CKPT_DIR = os.path.join(BASE, "checkpoints")
PRED_CACHE_DIR = os.path.join(CKPT_DIR, "prediction_cache")

TEST_JSON = os.path.join(CKPT_DIR, "test_samples_ssim.json")
BEST_STRATEGY_JSON = os.path.join(CKPT_DIR, "best_strategy_tta_ensemble.json")

CLASS_NAMES = ["Good", "Moderate", "Bad"]


def find_latest_cache(pattern: str) -> str:
    files = glob.glob(os.path.join(PRED_CACHE_DIR, pattern))
    if not files:
        raise FileNotFoundError(f"No cache found for pattern: {pattern}")
    files = sorted(files, key=os.path.getmtime, reverse=True)
    return files[0]


def apply_thresholds(probabilities: np.ndarray, thresholds: np.ndarray) -> np.ndarray:
    thresholds = np.asarray(thresholds, dtype=np.float32).reshape(1, -1)
    return np.argmax(probabilities / thresholds, axis=1)


def majority_label(labels):
    return Counter(labels).most_common(1)[0][0]


def main():
    print("=" * 70)
    print("KMAR-50K Volume-Level Aggregation Evaluation")
    print("=" * 70)

    with open(TEST_JSON, "r") as f:
        test_samples = json.load(f)

    with open(BEST_STRATEGY_JSON, "r") as f:
        strategy = json.load(f)

    thresholds = np.array([
        strategy["thresholds"]["Good"],
        strategy["thresholds"]["Moderate"],
        strategy["thresholds"]["Bad"],
    ], dtype=np.float32)

    w3 = float(strategy.get("phase3_weight", 0.25))
    w5 = float(strategy.get("phase5_weight", 0.75))

    print(f"Strategy      : {strategy['strategy']}")
    print(f"Phase 3 weight: {w3}")
    print(f"Phase 5 weight: {w5}")
    print(f"Thresholds    : Good={thresholds[0]:.3f}, Moderate={thresholds[1]:.3f}, Bad={thresholds[2]:.3f}")

    # These caches were generated by apply_thresholds_tta_ensemble.py.
    # Phase 5 cache should use orig+hflip.
    phase3_cache = find_latest_cache("phase3_test_best_model_ssim_orig_*.npz")
    phase5_cache = find_latest_cache("phase5_test_best_model_phase5_orig_hflip_*.npz")

    print(f"\nPhase 3 cache : {phase3_cache}")
    print(f"Phase 5 cache : {phase5_cache}")

    p3 = np.load(phase3_cache)
    p5 = np.load(phase5_cache)

    p3_probs = p3["probs"]
    p5_probs = p5["probs"]
    y_true_slice = p5["q_true"]

    if len(test_samples) != len(p3_probs) or len(test_samples) != len(p5_probs):
        raise RuntimeError("Prediction cache length does not match test_samples_ssim.json")

    # Ensemble slice probabilities.
    ens_probs_slice = (w3 * p3_probs) + (w5 * p5_probs)

    # Slice-level sanity check.
    y_pred_slice = apply_thresholds(ens_probs_slice, thresholds)
    print("\n" + "=" * 70)
    print("SLICE-LEVEL CHECK — should match your previous best approximately")
    print("=" * 70)
    print(f"Slice Accuracy : {accuracy_score(y_true_slice, y_pred_slice) * 100:.2f}%")
    print(f"Slice Weighted F1: {f1_score(y_true_slice, y_pred_slice, average='weighted'):.4f}")
    print(classification_report(y_true_slice, y_pred_slice, target_names=CLASS_NAMES, digits=4))
    print("Confusion matrix [Good, Moderate, Bad]:")
    print(confusion_matrix(y_true_slice, y_pred_slice, labels=[0, 1, 2]))

    # Group by volume path.
    grouped_probs = defaultdict(list)
    grouped_true = defaultdict(list)

    for sample, probs, true_label in zip(test_samples, ens_probs_slice, y_true_slice):
        volume_key = sample["path"]
        grouped_probs[volume_key].append(probs)
        grouped_true[volume_key].append(int(true_label))

    y_true_vol_majority = []
    y_true_vol_worst = []
    y_pred_vol = []
    volume_rows = []

    for volume_path in sorted(grouped_probs.keys()):
        probs_arr = np.vstack(grouped_probs[volume_path])
        avg_probs = probs_arr.mean(axis=0)

        pred = apply_thresholds(avg_probs.reshape(1, -1), thresholds)[0]

        labels = grouped_true[volume_path]
        true_majority = majority_label(labels)
        true_worst = max(labels)  # strict clinical rule: if any slice is Bad, volume becomes Bad

        y_true_vol_majority.append(true_majority)
        y_true_vol_worst.append(true_worst)
        y_pred_vol.append(pred)

        volume_rows.append({
            "path": volume_path,
            "n_slices": len(labels),
            "true_majority": true_majority,
            "true_worst": true_worst,
            "pred": int(pred),
            "avg_good": float(avg_probs[0]),
            "avg_moderate": float(avg_probs[1]),
            "avg_bad": float(avg_probs[2]),
        })

    y_true_vol_majority = np.array(y_true_vol_majority)
    y_true_vol_worst = np.array(y_true_vol_worst)
    y_pred_vol = np.array(y_pred_vol)

    print("\n" + "=" * 70)
    print("VOLUME-LEVEL RESULT — majority slice label as volume truth")
    print("=" * 70)
    print(f"Volumes evaluated : {len(y_pred_vol)}")
    print(f"Volume Accuracy   : {accuracy_score(y_true_vol_majority, y_pred_vol) * 100:.2f}%")
    print(f"Volume Weighted F1: {f1_score(y_true_vol_majority, y_pred_vol, average='weighted'):.4f}")
    print(classification_report(y_true_vol_majority, y_pred_vol, target_names=CLASS_NAMES, digits=4))
    print("Confusion matrix [Good, Moderate, Bad]:")
    print(confusion_matrix(y_true_vol_majority, y_pred_vol, labels=[0, 1, 2]))

    print("\n" + "=" * 70)
    print("VOLUME-LEVEL RESULT — strict worst-slice label as volume truth")
    print("=" * 70)
    print("Note: this is stricter. A volume becomes Bad if any slice is Bad.")
    print(f"Volumes evaluated : {len(y_pred_vol)}")
    print(f"Volume Accuracy   : {accuracy_score(y_true_vol_worst, y_pred_vol) * 100:.2f}%")
    print(f"Volume Weighted F1: {f1_score(y_true_vol_worst, y_pred_vol, average='weighted'):.4f}")
    print(classification_report(y_true_vol_worst, y_pred_vol, target_names=CLASS_NAMES, digits=4))
    print("Confusion matrix [Good, Moderate, Bad]:")
    print(confusion_matrix(y_true_vol_worst, y_pred_vol, labels=[0, 1, 2]))

    out_json = os.path.join(CKPT_DIR, "volume_level_evaluation_rows.json")
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(volume_rows, f, indent=2)

    print(f"\n✅ Saved volume rows → {out_json}")


if __name__ == "__main__":
    main()